name: Deploy ไปยัง Firebase Hosting PROD
'on':
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/workflows/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hosting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
      - name: ติดตั้ง Firebase CLI
        run: npm install -g firebase-tools@latest
      - name: Create Service Account Key File
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}" > service_account.json
      - name: Deploy to Firebase Hosting and Functions
        run: |
          unset FIREBASE_TOKEN 
          unset GOOGLE_APPLICATION_CREDENTIALS
          export GOOGLE_APPLICATION_CREDENTIALS="./service_account.json" 
          firebase deploy --only hosting,functions --project pachara-shop --force --debug
