name: Deploy ไปยัง Firebase Hosting Dev
'on':
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ตรวจสอบตำแหน่งปัจจุบัน
        run: pwd
      - name: แสดงรายการไฟล์ใน Directory
        run: ls -al
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Copy .env.development to .env.production
        run: cp .env.development .env.production
      - name: Copy .env.development to .env.production
        run: cp .env.development .env.production
      - name: ตรวจสอบ .env.production
        run: cat .env.production
      - run: npm install
      - run: npm run build
      - name: ติดตั้ง Firebase CLI
        run: npm install -g firebase-tools@latest
      - name: Deploy ไปยัง Firebase Hosting และ Functions พร้อม Force
        run: |
          firebase experiments:enable webframeworks
          firebase deploy --only hosting,functions --project pachara-shop-dev --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_DEV_TOKEN }}
    defaults:
      run:
        working-directory: hosting
