name: Deploy ไปยัง Firebase Hosting Dev
'on':
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # หรือ version ที่คุณใช้
      - run: yarn install
      - run: yarn build
      - name: ติดตั้ง Firebase CLI
        run: npm install -g firebase-tools@latest # ใช้ latest version
      - name: Deploy ไปยัง Firebase Hosting และ Functions พร้อม Force
        run: firebase deploy --only hosting,functions --project pachara-shop-dev --force
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_DEPLOY_DEV_TOKEN }}'
