name: Deploy to Firebase Hosting on PR to dev
on:
  push:
    branches:
      - dev
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build project
        run: yarn build

      - name: Debug Info
        run: |
          echo "Node version:"
          node -v
          echo "Yarn version:"
          yarn -v
          echo "Installed packages:"
          yarn list

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PACHARA_SHOP_DEV }}'
          channelId: live
          projectId: pachara-shop-dev
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

    defaults:
      run:
        working-directory: hosting
