name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: yarn add esbuild
      - name: Copy .env.development to .env.production
        run: cp .env.development .env.production
      - run: yarn build
      - name: Install Firebase CLI
        run: yarn global add firebase-tools@13.29.1
      - name: Debug Node and Yarn versions
        run: |
          node -v
          yarn -v
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PACHARA_SHOP_DEV }}'
          channelId: live
          projectId: pachara-shop-dev
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
    defaults:
      run:
        working-directory: hosting
